/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.game.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.uno.game.Draw;
import org.xtext.example.uno.game.GamePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Draw</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.uno.game.impl.DrawImpl#getOneCard <em>One Card</em>}</li>
 *   <li>{@link org.xtext.example.uno.game.impl.DrawImpl#getThreeCards <em>Three Cards</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DrawImpl extends MinimalEObjectImpl.Container implements Draw
{
  /**
   * The default value of the '{@link #getOneCard() <em>One Card</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOneCard()
   * @generated
   * @ordered
   */
  protected static final String ONE_CARD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOneCard() <em>One Card</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOneCard()
   * @generated
   * @ordered
   */
  protected String oneCard = ONE_CARD_EDEFAULT;

  /**
   * The default value of the '{@link #getThreeCards() <em>Three Cards</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThreeCards()
   * @generated
   * @ordered
   */
  protected static final String THREE_CARDS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getThreeCards() <em>Three Cards</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThreeCards()
   * @generated
   * @ordered
   */
  protected String threeCards = THREE_CARDS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DrawImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.DRAW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOneCard()
  {
    return oneCard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOneCard(String newOneCard)
  {
    String oldOneCard = oneCard;
    oneCard = newOneCard;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.DRAW__ONE_CARD, oldOneCard, oneCard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getThreeCards()
  {
    return threeCards;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThreeCards(String newThreeCards)
  {
    String oldThreeCards = threeCards;
    threeCards = newThreeCards;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.DRAW__THREE_CARDS, oldThreeCards, threeCards));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.DRAW__ONE_CARD:
        return getOneCard();
      case GamePackage.DRAW__THREE_CARDS:
        return getThreeCards();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.DRAW__ONE_CARD:
        setOneCard((String)newValue);
        return;
      case GamePackage.DRAW__THREE_CARDS:
        setThreeCards((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.DRAW__ONE_CARD:
        setOneCard(ONE_CARD_EDEFAULT);
        return;
      case GamePackage.DRAW__THREE_CARDS:
        setThreeCards(THREE_CARDS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.DRAW__ONE_CARD:
        return ONE_CARD_EDEFAULT == null ? oneCard != null : !ONE_CARD_EDEFAULT.equals(oneCard);
      case GamePackage.DRAW__THREE_CARDS:
        return THREE_CARDS_EDEFAULT == null ? threeCards != null : !THREE_CARDS_EDEFAULT.equals(threeCards);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (oneCard: ");
    result.append(oneCard);
    result.append(", threeCards: ");
    result.append(threeCards);
    result.append(')');
    return result.toString();
  }

} //DrawImpl
