/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.uno.game.Game#getTwoPlayers <em>Two Players</em>}</li>
 *   <li>{@link org.xtext.example.uno.game.Game#getTime <em>Time</em>}</li>
 *   <li>{@link org.xtext.example.uno.game.Game#getRotatingCards <em>Rotating Cards</em>}</li>
 *   <li>{@link org.xtext.example.uno.game.Game#getPlayingSameCards <em>Playing Same Cards</em>}</li>
 *   <li>{@link org.xtext.example.uno.game.Game#getDraw <em>Draw</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.uno.game.GamePackage#getGame()
 * @model
 * @generated
 */
public interface Game extends EObject
{
  /**
   * Returns the value of the '<em><b>Two Players</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Two Players</em>' attribute.
   * @see #setTwoPlayers(String)
   * @see org.xtext.example.uno.game.GamePackage#getGame_TwoPlayers()
   * @model
   * @generated
   */
  String getTwoPlayers();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.game.Game#getTwoPlayers <em>Two Players</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Two Players</em>' attribute.
   * @see #getTwoPlayers()
   * @generated
   */
  void setTwoPlayers(String value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Time)
   * @see org.xtext.example.uno.game.GamePackage#getGame_Time()
   * @model containment="true"
   * @generated
   */
  Time getTime();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.game.Game#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Time value);

  /**
   * Returns the value of the '<em><b>Rotating Cards</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rotating Cards</em>' containment reference.
   * @see #setRotatingCards(RotatingCards)
   * @see org.xtext.example.uno.game.GamePackage#getGame_RotatingCards()
   * @model containment="true"
   * @generated
   */
  RotatingCards getRotatingCards();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.game.Game#getRotatingCards <em>Rotating Cards</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rotating Cards</em>' containment reference.
   * @see #getRotatingCards()
   * @generated
   */
  void setRotatingCards(RotatingCards value);

  /**
   * Returns the value of the '<em><b>Playing Same Cards</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Playing Same Cards</em>' containment reference.
   * @see #setPlayingSameCards(PlayingSameCards)
   * @see org.xtext.example.uno.game.GamePackage#getGame_PlayingSameCards()
   * @model containment="true"
   * @generated
   */
  PlayingSameCards getPlayingSameCards();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.game.Game#getPlayingSameCards <em>Playing Same Cards</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Playing Same Cards</em>' containment reference.
   * @see #getPlayingSameCards()
   * @generated
   */
  void setPlayingSameCards(PlayingSameCards value);

  /**
   * Returns the value of the '<em><b>Draw</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Draw</em>' containment reference.
   * @see #setDraw(Draw)
   * @see org.xtext.example.uno.game.GamePackage#getGame_Draw()
   * @model containment="true"
   * @generated
   */
  Draw getDraw();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.game.Game#getDraw <em>Draw</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Draw</em>' containment reference.
   * @see #getDraw()
   * @generated
   */
  void setDraw(Draw value);

} // Game
