/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.game;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.uno.game.GameFactory
 * @model kind="package"
 * @generated
 */
public interface GamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "game";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/uno/Game";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "game";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GamePackage eINSTANCE = org.xtext.example.uno.game.impl.GamePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.uno.game.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.game.impl.GameImpl
   * @see org.xtext.example.uno.game.impl.GamePackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Two Players</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__TWO_PLAYERS = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__TIME = 1;

  /**
   * The feature id for the '<em><b>Rotating Cards</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__ROTATING_CARDS = 2;

  /**
   * The feature id for the '<em><b>Playing Same Cards</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__PLAYING_SAME_CARDS = 3;

  /**
   * The feature id for the '<em><b>Draw</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__DRAW = 4;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.game.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.game.impl.TimeImpl
   * @see org.xtext.example.uno.game.impl.GamePackageImpl#getTime()
   * @generated
   */
  int TIME = 1;

  /**
   * The feature id for the '<em><b>Limited</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__LIMITED = 0;

  /**
   * The feature id for the '<em><b>Unlimited</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__UNLIMITED = 1;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.game.impl.RotatingCardsImpl <em>Rotating Cards</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.game.impl.RotatingCardsImpl
   * @see org.xtext.example.uno.game.impl.GamePackageImpl#getRotatingCards()
   * @generated
   */
  int ROTATING_CARDS = 2;

  /**
   * The feature id for the '<em><b>Rotating Zero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATING_CARDS__ROTATING_ZERO = 0;

  /**
   * The feature id for the '<em><b>Rotating Seven</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATING_CARDS__ROTATING_SEVEN = 1;

  /**
   * The number of structural features of the '<em>Rotating Cards</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATING_CARDS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.game.impl.PlayingSameCardsImpl <em>Playing Same Cards</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.game.impl.PlayingSameCardsImpl
   * @see org.xtext.example.uno.game.impl.GamePackageImpl#getPlayingSameCards()
   * @generated
   */
  int PLAYING_SAME_CARDS = 3;

  /**
   * The feature id for the '<em><b>Same Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYING_SAME_CARDS__SAME_NUMBER = 0;

  /**
   * The feature id for the '<em><b>Same Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYING_SAME_CARDS__SAME_COLOR = 1;

  /**
   * The number of structural features of the '<em>Playing Same Cards</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYING_SAME_CARDS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.game.impl.DrawImpl <em>Draw</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.game.impl.DrawImpl
   * @see org.xtext.example.uno.game.impl.GamePackageImpl#getDraw()
   * @generated
   */
  int DRAW = 4;

  /**
   * The feature id for the '<em><b>One Card</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRAW__ONE_CARD = 0;

  /**
   * The feature id for the '<em><b>Three Cards</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRAW__THREE_CARDS = 1;

  /**
   * The number of structural features of the '<em>Draw</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRAW_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.uno.game.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see org.xtext.example.uno.game.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.Game#getTwoPlayers <em>Two Players</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Two Players</em>'.
   * @see org.xtext.example.uno.game.Game#getTwoPlayers()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_TwoPlayers();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.uno.game.Game#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.example.uno.game.Game#getTime()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Time();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.uno.game.Game#getRotatingCards <em>Rotating Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rotating Cards</em>'.
   * @see org.xtext.example.uno.game.Game#getRotatingCards()
   * @see #getGame()
   * @generated
   */
  EReference getGame_RotatingCards();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.uno.game.Game#getPlayingSameCards <em>Playing Same Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Playing Same Cards</em>'.
   * @see org.xtext.example.uno.game.Game#getPlayingSameCards()
   * @see #getGame()
   * @generated
   */
  EReference getGame_PlayingSameCards();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.uno.game.Game#getDraw <em>Draw</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Draw</em>'.
   * @see org.xtext.example.uno.game.Game#getDraw()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Draw();

  /**
   * Returns the meta object for class '{@link org.xtext.example.uno.game.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.example.uno.game.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.Time#getLimited <em>Limited</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Limited</em>'.
   * @see org.xtext.example.uno.game.Time#getLimited()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Limited();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.Time#getUnlimited <em>Unlimited</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unlimited</em>'.
   * @see org.xtext.example.uno.game.Time#getUnlimited()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Unlimited();

  /**
   * Returns the meta object for class '{@link org.xtext.example.uno.game.RotatingCards <em>Rotating Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotating Cards</em>'.
   * @see org.xtext.example.uno.game.RotatingCards
   * @generated
   */
  EClass getRotatingCards();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.RotatingCards#getRotatingZero <em>Rotating Zero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rotating Zero</em>'.
   * @see org.xtext.example.uno.game.RotatingCards#getRotatingZero()
   * @see #getRotatingCards()
   * @generated
   */
  EAttribute getRotatingCards_RotatingZero();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.RotatingCards#getRotatingSeven <em>Rotating Seven</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rotating Seven</em>'.
   * @see org.xtext.example.uno.game.RotatingCards#getRotatingSeven()
   * @see #getRotatingCards()
   * @generated
   */
  EAttribute getRotatingCards_RotatingSeven();

  /**
   * Returns the meta object for class '{@link org.xtext.example.uno.game.PlayingSameCards <em>Playing Same Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Playing Same Cards</em>'.
   * @see org.xtext.example.uno.game.PlayingSameCards
   * @generated
   */
  EClass getPlayingSameCards();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.PlayingSameCards#getSameNumber <em>Same Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Same Number</em>'.
   * @see org.xtext.example.uno.game.PlayingSameCards#getSameNumber()
   * @see #getPlayingSameCards()
   * @generated
   */
  EAttribute getPlayingSameCards_SameNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.PlayingSameCards#getSameColor <em>Same Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Same Color</em>'.
   * @see org.xtext.example.uno.game.PlayingSameCards#getSameColor()
   * @see #getPlayingSameCards()
   * @generated
   */
  EAttribute getPlayingSameCards_SameColor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.uno.game.Draw <em>Draw</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Draw</em>'.
   * @see org.xtext.example.uno.game.Draw
   * @generated
   */
  EClass getDraw();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.Draw#getOneCard <em>One Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>One Card</em>'.
   * @see org.xtext.example.uno.game.Draw#getOneCard()
   * @see #getDraw()
   * @generated
   */
  EAttribute getDraw_OneCard();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.game.Draw#getThreeCards <em>Three Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Three Cards</em>'.
   * @see org.xtext.example.uno.game.Draw#getThreeCards()
   * @see #getDraw()
   * @generated
   */
  EAttribute getDraw_ThreeCards();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameFactory getGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.uno.game.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.game.impl.GameImpl
     * @see org.xtext.example.uno.game.impl.GamePackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Two Players</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__TWO_PLAYERS = eINSTANCE.getGame_TwoPlayers();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__TIME = eINSTANCE.getGame_Time();

    /**
     * The meta object literal for the '<em><b>Rotating Cards</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__ROTATING_CARDS = eINSTANCE.getGame_RotatingCards();

    /**
     * The meta object literal for the '<em><b>Playing Same Cards</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__PLAYING_SAME_CARDS = eINSTANCE.getGame_PlayingSameCards();

    /**
     * The meta object literal for the '<em><b>Draw</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__DRAW = eINSTANCE.getGame_Draw();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.game.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.game.impl.TimeImpl
     * @see org.xtext.example.uno.game.impl.GamePackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Limited</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__LIMITED = eINSTANCE.getTime_Limited();

    /**
     * The meta object literal for the '<em><b>Unlimited</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__UNLIMITED = eINSTANCE.getTime_Unlimited();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.game.impl.RotatingCardsImpl <em>Rotating Cards</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.game.impl.RotatingCardsImpl
     * @see org.xtext.example.uno.game.impl.GamePackageImpl#getRotatingCards()
     * @generated
     */
    EClass ROTATING_CARDS = eINSTANCE.getRotatingCards();

    /**
     * The meta object literal for the '<em><b>Rotating Zero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATING_CARDS__ROTATING_ZERO = eINSTANCE.getRotatingCards_RotatingZero();

    /**
     * The meta object literal for the '<em><b>Rotating Seven</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATING_CARDS__ROTATING_SEVEN = eINSTANCE.getRotatingCards_RotatingSeven();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.game.impl.PlayingSameCardsImpl <em>Playing Same Cards</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.game.impl.PlayingSameCardsImpl
     * @see org.xtext.example.uno.game.impl.GamePackageImpl#getPlayingSameCards()
     * @generated
     */
    EClass PLAYING_SAME_CARDS = eINSTANCE.getPlayingSameCards();

    /**
     * The meta object literal for the '<em><b>Same Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLAYING_SAME_CARDS__SAME_NUMBER = eINSTANCE.getPlayingSameCards_SameNumber();

    /**
     * The meta object literal for the '<em><b>Same Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLAYING_SAME_CARDS__SAME_COLOR = eINSTANCE.getPlayingSameCards_SameColor();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.game.impl.DrawImpl <em>Draw</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.game.impl.DrawImpl
     * @see org.xtext.example.uno.game.impl.GamePackageImpl#getDraw()
     * @generated
     */
    EClass DRAW = eINSTANCE.getDraw();

    /**
     * The meta object literal for the '<em><b>One Card</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRAW__ONE_CARD = eINSTANCE.getDraw_OneCard();

    /**
     * The meta object literal for the '<em><b>Three Cards</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRAW__THREE_CARDS = eINSTANCE.getDraw_ThreeCards();

  }

} //GamePackage
