/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.uno.game.Time#getLimited <em>Limited</em>}</li>
 *   <li>{@link org.xtext.example.uno.game.Time#getUnlimited <em>Unlimited</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.uno.game.GamePackage#getTime()
 * @model
 * @generated
 */
public interface Time extends EObject
{
  /**
   * Returns the value of the '<em><b>Limited</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Limited</em>' attribute.
   * @see #setLimited(String)
   * @see org.xtext.example.uno.game.GamePackage#getTime_Limited()
   * @model
   * @generated
   */
  String getLimited();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.game.Time#getLimited <em>Limited</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Limited</em>' attribute.
   * @see #getLimited()
   * @generated
   */
  void setLimited(String value);

  /**
   * Returns the value of the '<em><b>Unlimited</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unlimited</em>' attribute.
   * @see #setUnlimited(String)
   * @see org.xtext.example.uno.game.GamePackage#getTime_Unlimited()
   * @model
   * @generated
   */
  String getUnlimited();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.game.Time#getUnlimited <em>Unlimited</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unlimited</em>' attribute.
   * @see #getUnlimited()
   * @generated
   */
  void setUnlimited(String value);

} // Time
